name: Starred Repos
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  starred-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Recently starred
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3
